#!/bin/bash

# A script to add new syntax/ftdetect/indent files to /etc/vim.
#
# This script assumes that the files to be moved is in the `vim` directory, in
# their respective syntax/ftdetect/indent subdirectories, and has the same filename
# (preferrably for the language for which they will be used).
#
# Example usage: ./vimupdate jinja

check_and_copy(){
    if [ -f ./vim/$1/$2.vim ]; then
        sudo cp ./vim/$1/$2.vim /etc/vim/$1
    fi
}

sudo mkdir -p /etc/vim/syntax
sudo mkdir -p /etc/vim/ftdetect
sudo mkdir -p /etc/vim/indent

sudo cp ./vim/vimrc /etc/vim

check_and_copy ftdetect $1
check_and_copy ftplugin $1
check_and_copy indent $1
check_and_copy syntax $1
