#! /usr/bin/bash

# A collection of installs for my preferred Ubuntu customizations.

# Install virtualenv via virtualenv burrito
curl -sL https://raw.githubusercontent.com/brainsik/virtualenv-burrito/master/virtualenv-burrito.sh | $SHELL

##########################
# Add all PPA's here
##########################
sudo add-apt-repository ppa:webupd8team/java
# For `hub`. I can live without this so this _might_ go some time in the future
# https://github.com/github/hub/issues/718
sudo add-apt-repository ppa:cpick/hub


sudo apt-get update

sudo apt-get install -y compizconfig-settings-manager hub oracle-java8-installer ppa-purge traceroute tree unity-tweak-tool xclip
