#! /usr/bin/bash

# A collection of installs for my preferred Ubuntu customizations.

# Install virtualenv via virtualenv burrito
curl -sL https://raw.githubusercontent.com/brainsik/virtualenv-burrito/master/virtualenv-burrito.sh | $SHELL

# Add all PPA's here
sudo add-apt-repository ppa:webupd8team/java

sudo apt-get update

sudo apt-get install -y compizconfig-settings-manager oracle-java8-installer tree unity-tweak-tool xclip
