#! /bin/bash

# A collection of installs for my preferred Ubuntu customizations.

# Install virtualenv via virtualenv burrito
if [ ! -d ~/.virtualenvs ]; then
    curl -sL https://raw.githubusercontent.com/brainsik/virtualenv-burrito/master/virtualenv-burrito.sh | $SHELL
fi

##########################
# Add all PPA's here
##########################
sudo add-apt-repository -y ppa:webupd8team/java

sudo apt-get update

sudo apt-get install -y compizconfig-settings-manager ppa-purge traceroute tree unity-tweak-tool vim xclip
sudo apt-get install -y oracle-java8-installer
